apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  hostNetwork: true
  containers:

  - name: microk8s-webconsole-ui
    image: stavrosdro/microk8s-webconsole_ui:1.0
    ports:
      - containerPort: 4200

  - name: microk8s-webconsole-server
    image: stavrosdro/microk8s-webconsole_server:1.0
    volumeMounts:
    - name: myvolume
      mountPath: /myvolume/env.json
      subPath: env.json
      readOnly: true

  volumes:
  - name: myvolume
    secret:
      secretName: mysecret
