version: '3'
services:
  server:
    container_name: server-docker-node
    environment:
      HOST_PASSWORD: ${HOST_PASSWORD}
      HOST_USERNAME: ${HOST_USERNAME}
      HOST_IP: ${HOST_IP}
    build: ./server/
    ports:
      - 3000:3000
    links:
      - ui
  ui:
    container_name: ui-docker-node
    build: ./ui/
    network_mode: host
    ports: 
      - 4200:4200
